# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import axiom_pb2 as axiom__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in axiom_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CausalServiceStub(object):
    """── CausalService ──────────────────────────────────
    Python gRPC server (port 50051)
    Causal engine internal calls

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuildGraph = channel.unary_unary(
                '/axiom.CausalService/BuildGraph',
                request_serializer=axiom__pb2.BuildGraphRequest.SerializeToString,
                response_deserializer=axiom__pb2.GraphResponse.FromString,
                _registered_method=True)
        self.GetGraph = channel.unary_unary(
                '/axiom.CausalService/GetGraph',
                request_serializer=axiom__pb2.GetGraphRequest.SerializeToString,
                response_deserializer=axiom__pb2.GraphResponse.FromString,
                _registered_method=True)
        self.GetEffects = channel.unary_unary(
                '/axiom.CausalService/GetEffects',
                request_serializer=axiom__pb2.GetEffectsRequest.SerializeToString,
                response_deserializer=axiom__pb2.EffectsResponse.FromString,
                _registered_method=True)


class CausalServiceServicer(object):
    """── CausalService ──────────────────────────────────
    Python gRPC server (port 50051)
    Causal engine internal calls

    """

    def BuildGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEffects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CausalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuildGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildGraph,
                    request_deserializer=axiom__pb2.BuildGraphRequest.FromString,
                    response_serializer=axiom__pb2.GraphResponse.SerializeToString,
            ),
            'GetGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraph,
                    request_deserializer=axiom__pb2.GetGraphRequest.FromString,
                    response_serializer=axiom__pb2.GraphResponse.SerializeToString,
            ),
            'GetEffects': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEffects,
                    request_deserializer=axiom__pb2.GetEffectsRequest.FromString,
                    response_serializer=axiom__pb2.EffectsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axiom.CausalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('axiom.CausalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CausalService(object):
    """── CausalService ──────────────────────────────────
    Python gRPC server (port 50051)
    Causal engine internal calls

    """

    @staticmethod
    def BuildGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axiom.CausalService/BuildGraph',
            axiom__pb2.BuildGraphRequest.SerializeToString,
            axiom__pb2.GraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axiom.CausalService/GetGraph',
            axiom__pb2.GetGraphRequest.SerializeToString,
            axiom__pb2.GraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEffects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axiom.CausalService/GetEffects',
            axiom__pb2.GetEffectsRequest.SerializeToString,
            axiom__pb2.EffectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ZKBridgeServiceStub(object):
    """── ZKBridgeService ────────────────────────────────
    Rust tonic gRPC server (port 50052)
    ZK proof generation for high throughput

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateProof = channel.unary_unary(
                '/axiom.ZKBridgeService/GenerateProof',
                request_serializer=axiom__pb2.ProofRequest.SerializeToString,
                response_deserializer=axiom__pb2.ProofResponse.FromString,
                _registered_method=True)
        self.VerifyProof = channel.unary_unary(
                '/axiom.ZKBridgeService/VerifyProof',
                request_serializer=axiom__pb2.VerifyRequest.SerializeToString,
                response_deserializer=axiom__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.BatchProof = channel.unary_stream(
                '/axiom.ZKBridgeService/BatchProof',
                request_serializer=axiom__pb2.BatchProofRequest.SerializeToString,
                response_deserializer=axiom__pb2.ProofResponse.FromString,
                _registered_method=True)


class ZKBridgeServiceServicer(object):
    """── ZKBridgeService ────────────────────────────────
    Rust tonic gRPC server (port 50052)
    ZK proof generation for high throughput

    """

    def GenerateProof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyProof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchProof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZKBridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateProof': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateProof,
                    request_deserializer=axiom__pb2.ProofRequest.FromString,
                    response_serializer=axiom__pb2.ProofResponse.SerializeToString,
            ),
            'VerifyProof': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyProof,
                    request_deserializer=axiom__pb2.VerifyRequest.FromString,
                    response_serializer=axiom__pb2.VerifyResponse.SerializeToString,
            ),
            'BatchProof': grpc.unary_stream_rpc_method_handler(
                    servicer.BatchProof,
                    request_deserializer=axiom__pb2.BatchProofRequest.FromString,
                    response_serializer=axiom__pb2.ProofResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axiom.ZKBridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('axiom.ZKBridgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ZKBridgeService(object):
    """── ZKBridgeService ────────────────────────────────
    Rust tonic gRPC server (port 50052)
    ZK proof generation for high throughput

    """

    @staticmethod
    def GenerateProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axiom.ZKBridgeService/GenerateProof',
            axiom__pb2.ProofRequest.SerializeToString,
            axiom__pb2.ProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axiom.ZKBridgeService/VerifyProof',
            axiom__pb2.VerifyRequest.SerializeToString,
            axiom__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/axiom.ZKBridgeService/BatchProof',
            axiom__pb2.BatchProofRequest.SerializeToString,
            axiom__pb2.ProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SurvivalServiceStub(object):
    """── SurvivalService ────────────────────────────────
    Python gRPC server (port 50053)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/axiom.SurvivalService/Predict',
                request_serializer=axiom__pb2.PredictRequest.SerializeToString,
                response_deserializer=axiom__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.Recommend = channel.unary_unary(
                '/axiom.SurvivalService/Recommend',
                request_serializer=axiom__pb2.RecommendRequest.SerializeToString,
                response_deserializer=axiom__pb2.RecommendResponse.FromString,
                _registered_method=True)


class SurvivalServiceServicer(object):
    """── SurvivalService ────────────────────────────────
    Python gRPC server (port 50053)

    """

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recommend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SurvivalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=axiom__pb2.PredictRequest.FromString,
                    response_serializer=axiom__pb2.PredictResponse.SerializeToString,
            ),
            'Recommend': grpc.unary_unary_rpc_method_handler(
                    servicer.Recommend,
                    request_deserializer=axiom__pb2.RecommendRequest.FromString,
                    response_serializer=axiom__pb2.RecommendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axiom.SurvivalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('axiom.SurvivalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SurvivalService(object):
    """── SurvivalService ────────────────────────────────
    Python gRPC server (port 50053)

    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axiom.SurvivalService/Predict',
            axiom__pb2.PredictRequest.SerializeToString,
            axiom__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recommend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axiom.SurvivalService/Recommend',
            axiom__pb2.RecommendRequest.SerializeToString,
            axiom__pb2.RecommendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FederatedServiceStub(object):
    """── FederatedService ───────────────────────────────
    Rust tonic gRPC server (port 50054)
    High-throughput gradient streaming

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunRound = channel.unary_unary(
                '/axiom.FederatedService/RunRound',
                request_serializer=axiom__pb2.RoundRequest.SerializeToString,
                response_deserializer=axiom__pb2.RoundResponse.FromString,
                _registered_method=True)
        self.GetWeights = channel.unary_unary(
                '/axiom.FederatedService/GetWeights',
                request_serializer=axiom__pb2.WeightsRequest.SerializeToString,
                response_deserializer=axiom__pb2.WeightsResponse.FromString,
                _registered_method=True)
        self.StreamGradients = channel.stream_unary(
                '/axiom.FederatedService/StreamGradients',
                request_serializer=axiom__pb2.GradientUpdate.SerializeToString,
                response_deserializer=axiom__pb2.AggregationResult.FromString,
                _registered_method=True)


class FederatedServiceServicer(object):
    """── FederatedService ───────────────────────────────
    Rust tonic gRPC server (port 50054)
    High-throughput gradient streaming

    """

    def RunRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGradients(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunRound': grpc.unary_unary_rpc_method_handler(
                    servicer.RunRound,
                    request_deserializer=axiom__pb2.RoundRequest.FromString,
                    response_serializer=axiom__pb2.RoundResponse.SerializeToString,
            ),
            'GetWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeights,
                    request_deserializer=axiom__pb2.WeightsRequest.FromString,
                    response_serializer=axiom__pb2.WeightsResponse.SerializeToString,
            ),
            'StreamGradients': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamGradients,
                    request_deserializer=axiom__pb2.GradientUpdate.FromString,
                    response_serializer=axiom__pb2.AggregationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axiom.FederatedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('axiom.FederatedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedService(object):
    """── FederatedService ───────────────────────────────
    Rust tonic gRPC server (port 50054)
    High-throughput gradient streaming

    """

    @staticmethod
    def RunRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axiom.FederatedService/RunRound',
            axiom__pb2.RoundRequest.SerializeToString,
            axiom__pb2.RoundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axiom.FederatedService/GetWeights',
            axiom__pb2.WeightsRequest.SerializeToString,
            axiom__pb2.WeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGradients(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/axiom.FederatedService/StreamGradients',
            axiom__pb2.GradientUpdate.SerializeToString,
            axiom__pb2.AggregationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AlertServiceStub(object):
    """── AlertService ───────────────────────────────────
    Python gRPC server (embedded in NLP service)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/axiom.AlertService/Subscribe',
                request_serializer=axiom__pb2.AlertSubscribeRequest.SerializeToString,
                response_deserializer=axiom__pb2.AlertEvent.FromString,
                _registered_method=True)
        self.Acknowledge = channel.unary_unary(
                '/axiom.AlertService/Acknowledge',
                request_serializer=axiom__pb2.AcknowledgeRequest.SerializeToString,
                response_deserializer=axiom__pb2.AcknowledgeResponse.FromString,
                _registered_method=True)


class AlertServiceServicer(object):
    """── AlertService ───────────────────────────────────
    Python gRPC server (embedded in NLP service)

    """

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Acknowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlertServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=axiom__pb2.AlertSubscribeRequest.FromString,
                    response_serializer=axiom__pb2.AlertEvent.SerializeToString,
            ),
            'Acknowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.Acknowledge,
                    request_deserializer=axiom__pb2.AcknowledgeRequest.FromString,
                    response_serializer=axiom__pb2.AcknowledgeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axiom.AlertService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('axiom.AlertService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlertService(object):
    """── AlertService ───────────────────────────────────
    Python gRPC server (embedded in NLP service)

    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/axiom.AlertService/Subscribe',
            axiom__pb2.AlertSubscribeRequest.SerializeToString,
            axiom__pb2.AlertEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Acknowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axiom.AlertService/Acknowledge',
            axiom__pb2.AcknowledgeRequest.SerializeToString,
            axiom__pb2.AcknowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
