global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    project: axiom
    env: development

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: axiom_fhir_adapter
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: /actuator/prometheus
    scrape_interval: 15s

  - job_name: axiom_normalisation
    static_configs:
      - targets: ["host.docker.internal:8086"]
    metrics_path: /metrics
    scrape_interval: 15s