apiVersion: v1
kind: ConfigMap
metadata:
  name: axiom-config
  namespace: axiom-clinical
data:
  KAFKA_BOOTSTRAP: "kafka:9092"
  CAUSAL_ENGINE_URL: "http://causal-engine:8081"
  SURVIVAL_URL: "http://survival-service:8082"
  NLP_URL: "http://nlp-service:8083"
  ZK_URL: "http://zk-service:8084"
  FEDERATED_URL: "http://federated-service:8085"
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
